### PR TITLE
mapping Author to Author(s) ID

### PR DESCRIPTION
**Pull request by yuenfu001**
the methodology used: splitted the Authors and Author(s) ID columns into 4 columns each containing unique names and IDs respectively then merged the new data frames with the master df after which the original Authors and Author(s) ID were removed and new columns for Authors and Author(s) ID was rearranged.

### CODE REVIEW

**Comment by rahulgundre** [comment]
There is a conflict while pulling request. Please do the necessary corrections

**Comment by yuenfu001** [comment]
I didn't touch any of the codes , rather I added to the existing code

**Comment by yuenfu001** [comment]
but i will take a look at it again

**Comment by rahulgundre** [comment]
I am closing this pull request because we have move forward with removing columns with more than 60% null values

**Pull request closed without merging**
